name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: xcode-select
      run: sudo xcode-select -s /Applications/Xcode_12.2.app

    - name: get frameworks
      run: ./get_frameworks.sh

    - name: actual build
      run: set -o pipefail && xcodebuild archive -project Blink.xcodeproj -scheme Blink -sdk iphoneos -configuration Debug clean build IPHONEOS_DEPLOYMENT_TARGET='13.3' CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO ONLY_ACTIVE_ARCH=NO | tee build.log | xcpretty

    - name: generate unsigned debug ipa
      run: |
        cd ~
        mkdir Payload
        mv ~/Library/Developer/Xcode/Archives/*/*/Products/Applications/Blink.app ~/Payload/
        zip -r Blink.ipa Payload
    - name: upload ipa
      uses: actions/upload-artifact@v2.2.0
      with:
        name: 'BlinkShell'
        path: ~/Blink.ipa
